source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'https://git.coding.net/410900345/SukSpecsMirrors.git'   # 私有库

platform :ios, ‘8.0’

target :weexDemo do

 pod 'WeexSDK','~>0.9.5'
 pod 'WXDevtool',   '~>0.9.5'
 pod 'SDWebImage', '3.7.5'
 pod 'ATSDK-Weex', '~> 0.0.1'
 pod 'SocketRocket', '0.4.2'
 pod 'MBProgressHUD', '~> 0.9.2'
 pod 'SSCategoriesSDK','~> 0.3.8' #通用扩展
 pod 'YYModel', '~> 1.0.1' #转模型
end
