source 'https://github.com/CocoaPods/Specs.git'  # 官方库


platform :ios, ‘8.0’

target :weexDemo do

 pod 'WeexSDK', '~>0.9.5'
 pod 'WXDevtool',   '~>0.9.5'
 pod 'SDWebImage', '3.7.5'
 pod 'ATSDK-Weex', '~> 0.0.1'
 pod 'SocketRocket', '0.4.2' 
end
